algoritmo "LerMatriz"
var
  mat: vetor[1..3, 1..2] de Inteiro
  L, C: inteiro
inicio
    para L <- 1 ate 3 faca
       para C <- 1 ate 2 faca
          EscrevaL ("Digite um valor da posicao [" , L, ",", c,"]: ")
          Leia (mat[L,C])
       FimPara
    FimPara
    
    Para L <- 1 ate 3 faca
       Para C <- 1 ate 2 faca
          Escreva (mat[L,C]: 5)
       FimPara
       EscrevaL ()
    FimPara
fimalgoritmo
